# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Cypress Test Automation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.5.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
         start: yarn run cy:chrome
         run: |
          echo "Waiting 15s to finish"
          sleep 15s

