# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Cypress Test Automation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.5.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    
    - name: Chrome headless
      uses: ./
      with:
          working-directory: ./chrome
          browser: chrome
          headless: true

    - uses: actions/upload-artifact@v2
      with:
          name: screenshots-in-headless-chrome
          path: ./chrome/cypress/screenshots

    - uses: actions/upload-artifact@v2
      with:
          name: video-in-headless-chrome
          path: ./chrome/cypress/videos

    - run: npx image-size cypress/screenshots/**/*.png
      working-directory: ./chrome